### ISSUE TITLE
Search Engine Implementation

### ISSUE THREAD

**Issue by sandipbhuyan** [librecores/librecores-web#242]
This issue deals with implementation of the search engine in LibreCores.org as described in #231 
## Tasks
- [x] Install Algolia
- [x] Index Project and Project Classifications
- [x] Implement autocomplete feature in the homepage
- [x] Implement instant search in browser project page
- [x] Searching through classifications
- [x] Search result display page
## Extended Task
- [x] Search display result through a project Classification
