### ISSUE TITLE
[GSoC 2019] Store notifications in the database

### ISSUE THREAD

**Issue by aquibbaig** [librecores/librecores-web#374]
- As discussed, the database schema needs to be updated for storing notifications of users. This issue will be an immediate follow up of #373. The notifications are supposed to be related to the Users table, so we should keep that in mind. 
- Also, DataFixtures are needed to be written for the above case.

### Tasks involved in this issue
- [x] Extend the database schema
- [x] Store Notifications in database
- [ ] Write DataFixtures for the above

### Further goals
 - This issue should deal with persisting the generated notification to the database so that they can be fetched to the UI afterward.

**Comment by imphil** [comment]
Try using https://packagist.org/packages/mgilet/notification-bundle

**Comment by aquibbaig** [comment]
The bundle above mentioned by @imphil comes with 3 class entities affecting our database schema

1. NotifiableEntity
2. NotifiableNotifications
3. Notification
- `Notifiable` entity is the entity you want notifications for, for example: User entity in our case
- `NotifiableNotification` entity holds the properties of the notifications i.e. if it has been seen. This entity is associated *ManyToOne* with Notifiable entity and Notification itself.
- `Notification` entity is the actual entity that holds the notification and it's fields like message, subject and so on. In our project, the Notification entity has been overriden by `AppNotification` entity as per our requirement to hold new fields such as the type of the Notification.

**Comment by aquibbaig** [comment]
![Entity](https://user-images.githubusercontent.com/26324376/60724352-c81daa00-9f53-11e9-890b-6ff756397875.jpg)

@imphil While creating an entity for Notifications, the following idea came to my mind:
- If we want to notify like many people with the same notification(such as notifying people in the whole org about a project creation), we need to make recipients as Array Collections and map it to the Users. While I have little knowledge about mappings as I am always confused in them, I have drawn out a basic structure, if that's okay. Please let me know what you think

**Comment by imphil** [comment]
It's better to have multiple `Notification`s in this case. It makes things much more complex, e.g. when you add status flags to a notification (like "has been read"). So 1:1 Notification : Recipient.
