### ISSUE TITLE
[GSoC 2019] Conveying Notifications to the user

### ISSUE THREAD

**Issue by aquibbaig** [librecores/librecores-web#375]
This issue will deal with the final part of the notification system design implementation. After the notifications are generated and stored, the final step is to fetch these notifications for any user and then two things can happen, based on the type of notification which has been stored. So, basically after fetching a notification, extract its type.
- If its type is **email**, send it to the appropriate email
- If its type is **web**, fetch it from the database and render it on the NavBar.

### Constraints
 - User cannot get any notification unless he is logged onto *Librecores*. Checks should be done to ensure the same

**Tasks to be achieved**
- [x] Fetch notifications from the database
- [x] Render Notifications on the UI
- [x] Run Test Notifications to have a reality check on to what extent things can be achieved
- [x] Associate each notification with a remove and mark-as-seen button that perform the required actions
- [x] Redirect to user dashboard to modify Notification Settings
- [x] Improve the Notification Panel UI

**Comment by aquibbaig** [comment]
I had some time to test out `mgilet notification bundle` and here's what I have achieved so far. The target event is notifying users when they create a project.
<img width="1437" alt="Screenshot 2019-06-07 at 6 28 42 PM" src="https://user-images.githubusercontent.com/26324376/59105788-5a7d5e80-8952-11e9-911c-5dd34ecc65ea.png">

**Comment by aquibbaig** [comment]
Tasks to be achieved
- [ ] Associate each notification with a remove and mark-as-seen button that perform the required actions
- [ ] Redirect to user dashboard to modify Notification Settings
- [ ] Improve the Notification Panel UI

**Comment by aquibbaig** [comment]
Well, I thought of a design and this is what we can do.
<img width="695" alt="Screenshot 2019-06-14 at 9 21 32 AM" src="https://user-images.githubusercontent.com/26324376/59482321-00b2f200-8e86-11e9-8cab-973aa658c48f.png">

**Comment by aquibbaig** [comment]
Fixed in #384 !
